# Logging configuration for Eidolon AI Personal Assistant

version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  json:
    format: "%(asctime)s"
    class: "pythonjsonlogger.jsonlogger.JsonFormatter"
    
handlers:
  console:
    class: "logging.StreamHandler"
    level: "INFO"
    formatter: "standard"
    stream: "ext://sys.stdout"
  
  file:
    class: "logging.handlers.RotatingFileHandler"
    level: "DEBUG"
    formatter: "detailed"
    filename: "./logs/eidolon.log"
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: "utf8"
  
  error_file:
    class: "logging.handlers.RotatingFileHandler"
    level: "ERROR"
    formatter: "detailed"
    filename: "./logs/eidolon_errors.log"
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: "utf8"

loggers:
  eidolon:
    level: "DEBUG"
    handlers: ["console", "file", "error_file"]
    propagate: false
  
  eidolon.core.observer:
    level: "INFO"
    handlers: ["file"]
    propagate: true
  
  eidolon.core.analyzer:
    level: "INFO" 
    handlers: ["file"]
    propagate: true
    
  eidolon.models:
    level: "WARNING"
    handlers: ["file"]
    propagate: true
    
  # External library logging
  transformers:
    level: "WARNING"
    handlers: ["file"]
    propagate: false
    
  chromadb:
    level: "WARNING"
    handlers: ["file"]
    propagate: false
    
  PIL:
    level: "ERROR"
    handlers: ["file"]
    propagate: false

root:
  level: "INFO"
  handlers: ["console", "file"]