# Eidolon AI Personal Assistant - High Performance Configuration
# Optimized for systems with 16GB+ RAM and modern hardware
# Copy this to settings.yaml for high-performance setups

# Observer settings for screenshot capture and monitoring
observer:
  # Screenshot capture settings
  capture_interval: 5                     # Faster capture for more data
  activity_threshold: 0.03               # More sensitive change detection
  storage_path: "./data/screenshots"     # Path for storing captured screenshots
  max_storage_gb: 100                    # Larger storage for high-frequency capture
  
  # Activity monitoring
  monitor_keyboard: true                 # Monitor keyboard activity
  monitor_mouse: true                    # Monitor mouse activity
  monitor_window_changes: true           # Monitor window focus changes
  
  # High-performance settings
  max_cpu_percent: 30.0                  # Allow higher CPU usage for AI processing
  max_memory_mb: 16384                   # 16GB for multiple AI models
  
  # Privacy settings
  sensitive_patterns:                    # Auto-redact these patterns
    - "password"
    - "api_key" 
    - "secret"
    - "token"
    - "ssn"
    - "credit_card"
  
  excluded_apps:                         # Don't monitor these applications
    - "1Password"
    - "Keychain Access"
    - "LastPass"
    - "Bitwarden"

# Analysis settings for AI processing
analysis:
  # Local AI models
  local_models:
    vision: "microsoft/florence-2-base"
    clip: "openai/clip-vit-base-patch32"
    embedding: "sentence-transformers/all-MiniLM-L6-v2"
    
  # High-performance AI settings
  performance:
    max_model_memory_gb: 8               # Allow larger models
    enable_model_caching: true           # Keep models in memory
    batch_processing: true               # Process multiple images at once
    gpu_acceleration: true               # Use GPU if available
    prefetch_models: true                # Load models on startup
    
  # Cloud AI APIs
  cloud_apis:
    gemini_key: "${GEMINI_API_KEY}"
    claude_key: "${CLAUDE_API_KEY}"
    openai_key: "${OPENAI_API_KEY}"
    
  # Routing logic for local vs cloud
  routing:
    importance_threshold: 0.5            # Lower threshold for cloud processing
    cost_limit_daily: 25.0              # Higher daily API cost limit (USD)
    local_first: true                    # Try local analysis first
    parallel_processing: true           # Process local and cloud simultaneously
    
  # OCR settings
  ocr:
    engine: "tesseract"                  # tesseract or easyocr
    languages: ["en"]                    # Language codes
    confidence_threshold: 0.5            # Lower threshold for more text extraction

# Memory system settings
memory:
  # Vector database
  vector_db: "chromadb"                  # chromadb, faiss, or pinecone
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  chunk_size: 1024                      # Larger chunks for better context
  overlap: 100                          # More overlap for continuity
  
  # Traditional database
  metadata_db: "sqlite"                 # sqlite or postgresql
  db_path: "./data/eidolon.db"         # Database file path
  
  # Search settings
  search:
    max_results: 100                    # More search results
    similarity_threshold: 0.6           # Lower threshold for more results
    enable_semantic_search: true       # Enable vector-based search
    enable_keyword_search: true        # Enable traditional keyword search
    enable_hybrid_search: true         # Combine multiple search methods

# Interface settings
interface:
  # CLI settings
  cli:
    default_output_format: "table"      # table, json, yaml
    show_timestamps: true               # Show timestamps in output
    show_confidence_scores: true       # Show AI confidence scores
    enable_rich_output: true           # Enhanced terminal output
    
  # Web interface settings  
  web:
    enabled: true                       # Enable web interface
    host: "localhost"                   # Web server host
    port: 8000                          # Web server port
    debug: false                        # Debug mode
    
  # API settings
  api:
    enabled: true                       # Enable REST API
    rate_limit: 1000                    # Higher requests per minute
    auth_required: false                # Require authentication

# Privacy and security settings
privacy:
  # Data handling
  local_only_mode: false                # Never send data to cloud APIs
  auto_redaction: true                  # Automatically redact sensitive info
  data_retention_days: 730             # Keep data for 2 years
  
  # Encryption
  encrypt_at_rest: true                # Encrypt stored data
  encryption_key_path: "./data/.key"   # Path to encryption key
  
  # User controls
  pause_on_sensitive_apps: true        # Auto-pause on sensitive applications
  require_confirmation_for_cloud: false # Ask before sending to cloud APIs

# Logging configuration
logging:
  level: "INFO"                        # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file_path: "./logs/eidolon.log"     # Log file path
  max_file_size_mb: 50                # Larger log files
  backup_count: 10                    # More backup files to keep
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Performance monitoring
monitoring:
  enabled: true                       # Enable performance monitoring
  metrics_collection_interval: 30    # More frequent metric collection
  alert_thresholds:
    cpu_percent: 40.0                 # Higher CPU threshold
    memory_mb: 20480                  # 20GB memory threshold
    disk_usage_percent: 85            # Disk usage threshold
    
  # Advanced monitoring
  detailed_metrics: true              # Collect detailed performance data
  ai_model_metrics: true              # Monitor AI model performance
  export_metrics: true                # Export metrics for analysis

# Development and debugging
development:
  debug_mode: false                   # Enable debug features
  mock_ai_responses: false           # Use mock responses for testing
  save_debug_screenshots: false     # Save intermediate processing images
  verbose_logging: false             # Extra detailed logging
  performance_profiling: true       # Enable performance profiling